preferred_syntax = :scss
http_path = '/'
css_dir = 'assets/css'
sass_dir = 'assets/css'
images_dir = 'assets/img'
javascripts_dir = 'assets/js'
relative_assets = true
line_comments = true
# output_style = :compressed